---
title: "PCAs and PerMANOVAs"
author: 
- name: Stephanie Hereira
  affiliation: Centro de Investigación y estudios avanzados del IPN
  email: shereirap@cinvestav.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r, warning=FALSE, message=FALSE}
#loading libraries
library(qiime2R)
library(tidyverse)
library(cowplot)
library(FactoMineR)
library(vegan)
library(ggpubr)
library(zCompositions)
library(compositions)

```

PCA plot all
```{r, warning=FALSE, message=FALSE}
#load file and correct zero values
table_240<- read_qza("../dada2.200.trimmed.single.filtered.cleaned.qza")$data %>% as.data.frame()
taxonomy_240<-  read_qza("../taxonomy_dada2.200.trimmed.single.seqs.qza")$data
metadata<- read.delim(file = "../RAW_DATA/MAPPINGSREV/FINALMAP", check.names = F) %>% filter(Month==2) %>% filter(!Type_of_soil=="Uncultivated")
table_240<- table_240 %>% dplyr::select_at(vars(!contains("US"))) %>% t() %>% as.data.frame() %>% rownames_to_column(var = "#SampleID") %>% inner_join(metadata) %>% filter(Month==2) %>% dplyr::select(-BarcodeSequence:-Description) %>% column_to_rownames(var = "#SampleID") %>% t()

#remove non-fungi taxa

taxonomy_filter<- taxonomy_240 %>% filter(
  !str_detect(Taxon, "ozoa"))%>% filter(
  !str_detect(Taxon, "helida")) %>% filter(
  !str_detect(Taxon, "ophyta")) %>% filter(
  !str_detect(Taxon, "Ciliophora")) %>% filter(
  !str_detect(Taxon, "Nucleariidae_and_Fonticula_group")) %>% filter(
  !str_detect(Taxon, "Arthrioida")) %>% filter(
  !str_detect(Taxon, "Labyrinthulomycetes"))  %>% filter(
  !str_detect(Taxon, "Apicomplexa")) %>% filter(
  !str_detect(Taxon, "Bicosoecida")) %>% filter(
  !str_detect(Taxon, "Breviatea")) %>% filter(
  !str_detect(Taxon, "Aphelidea"))  %>% filter(
  !str_detect(Taxon, "Arthropoda")) 

table_filter<-  table_240[match(
  taxonomy_filter$Feature.ID, rownames(table_240)),] %>%as.data.frame() %>%  drop_na(.)
table_filter<- table_240
#table_fil<- table_filter %>%filter(across(where(is.numeric), ~.x!=0)%>%reduce(`|`))
#d.pro.0<- table_fil %>% dplyr::select_at(vars(!contains("US")))%>%filter(across(where(is.numeric), ~.x!=0)%>%reduce(`|`))%>%   dplyr::select(where( ~ is.numeric(.x) && sum(.x) != 0))
#d.pro <- t(cmultRepl(t(d.pro.0), method="CZM", output="p-counts")) 

# make our compositional and run pca function
#d.clr.abund <- t(apply(d.pro, 2, function(x){log(x) - mean(log(x))}))
library(ALDEx2)
aldex.clr.transform <- aldex.clr(table_filter, mc.samples = 999, denom="all",
                                   verbose = FALSE, useMC=FALSE)
aldex.clr.transform.data <-  t(getMonteCarloSample(aldex.clr.transform,1) )
pcx.abund <- prcomp(aldex.clr.transform.data)


#load metadata and taxonomy file
meta<-metadata %>% 
  rename(SampleID=`#SampleID`) %>%
  filter(SampleID!="#q2:types")

meta$Compartment<- factor(meta$Type_of_soil,
                   levels = c( "Non-rizospheric", "Rizosphere", 
                               "Roots", "Uncultivated"),
                   labels = c("Bulk soil", "Rhizosphere",
                              "Roots", "Uncultivated"))
meta$Watering_regime<- factor(meta$Treatment,
                        levels = c( "0", "1", "2", "3"),
                        labels = c("Initial","Wet", "Dry", "Extreme dry"))


tax<-taxonomy_240
#Construsting PCA

#LABELS
PC1<- paste("PC1 : ", round(pcx.abund$sdev[1]^2/sum(pcx.abund$sdev^2),3)*100, "%",sep="")
PC2 <- paste("PC2 : ", round(pcx.abund$sdev[2]^2/sum(pcx.abund$sdev^2),3)*100, "%",sep="")


#SHAPES AND COLOR OF ARROWS


vars_chosen<- c("8dff1cb12c0beb5bc7b2546480a6a6c7", 
                "a33cb3037e7825920073b4dddaaa41e6",
                "74eb0ddf379b00c5032b18fb9fbf1f32", 
                "56025f74cc8e54d4a054442d786ef096",
                "8254e0f9f07709b62dd8483f3b25fad0")


vars_choosing<- data.frame(pcx.abund$rotation)%>%  rownames_to_column(
  var = "Feature.ID")%>%
  filter(Feature.ID %in% vars_chosen) %>%  mutate(a=sqrt(PC1^2+PC2^2)) %>%
  mutate(PC1=PC1*500, PC2=PC2*500) %>% left_join(tax)%>% dplyr::select(
    Taxon, PC1, PC2, Feature.ID)%>%mutate(tax= str_extract(Taxon, "[^_]+$")) %>% 
  mutate_at(c("tax"), funs(tax = case_when(
    tax=="herbarum" ~ "Cladosporium herbarum",
    TRUE~as.character(tax))))

color_type<- c("#800000", "#808000", "#008000", "#D35400", "#2E4053")

pca<- ggplot() +
  theme_bw()+
  xlab(PC1) +
  ylab(PC2) +
  geom_segment(data = vars_choosing, aes(x = 0, y = 0, xend = PC1, yend = PC2), 
               arrow=arrow(length=unit(0.15,"cm")),
               alpha = 0.75, color = 'black', size= 0.6)+
  theme(axis.text = element_text(colour = "black", size = 14),
        axis.title = element_text(colour = "black", size = 14),
         legend.text = element_text(size = 9),
        axis.ticks = element_line(colour = "black"),
        axis.line = element_line(colour = "black"),
        axis.text.y.right = element_text(colour = "black"),
        axis.text.x.top = element_text(colour = "black"),
        legend.position = "top", 
        legend.box = "vertical",
        legend.direction = "horizontal",
        legend.spacing.y = unit(0.01, 'cm'),
        legend.title = element_blank()) +
  geom_point(                              
    data=data.frame(pcx.abund$x) %>%   rownames_to_column(var = "SampleID")%>%
     inner_join(meta) %>% filter(!Compartment =="NA"),
    aes(x=PC1, y=PC2, color=Compartment, shape=Watering_regime), 
     size=5) + geom_vline(xintercept = 0, linetype = 2) +   
  geom_hline(yintercept = 0, linetype = 2)+
  scale_color_manual(values = color_type) +
  #scale_x_continuous(limits = c(-60,60))+
  ggrepel::geom_label_repel(data = vars_choosing, aes(x=PC1, y=PC2, label= tax),
  segment.colour = NA, col = 'black', fill= "#EEEEEE",
  fontface="bold.italic",  box.padding = 0.6, size=4)+ theme(
  plot.margin = unit(c(0.5, 1.5, 0.4, 0.1), "cm"))+
  guides(colour = guide_legend(override.aes = list(size=3)), 
         shape = guide_legend(override.aes = list(size = 3)))+
  theme(legend.text = element_text(size = 12))

pca

ggsave('pca_16S.pdf',    width = 6, height = 5, dpi = 300, plot =pca)
```


PERMANOVAs
```{r,message=FALSE, warning=FALSE, fig.width=3}

d.clr.abund2<- data.frame(aldex.clr.transform.data, check.names = F) %>% rownames_to_column(
  var = "ids") %>% filter(!str_detect(ids, 'US')) %>% column_to_rownames(
    var = "ids")

meta_just<- data.frame(d.clr.abund2, check.names = F) %>% rownames_to_column(
  var = "SampleID") %>% inner_join(meta) 


perm<- how(nperm = 999)
setBlocks(perm)<- with(meta_just, Plot)
ad_grouped<-adonis2(d.clr.abund2~Watering_regime*Compartment,
                    data = meta_just, method = "euclidian", 
                    permutations =999) %>% round(
                      ., digits = 3) %>%replace(is.na(.), "-")

tbody.style = tbody_style(color = "black",
   fill = c("white"), hjust=0, x=0.1)

Permanova_grouped <-data.frame(ad_grouped, check.names = F) %>% 
  rename("R^2" =  "R2", "p-value"="Pr(>F)") %>% 
  rownames_to_column( var="Factor") %>%
  mutate_at(3, funs(round(., 0)))  %>%
    mutate_at(5:6, as.numeric) %>% 
  mutate_at(4:5, funs(round(., 2))) %>% 
  mutate_at(5:6, ~replace(., is.na(.), "")) %>% 
    ggtexttable(., rows = NULL,  theme = ttheme(
             colnames.style = colnames_style(color = "black",                                            fill = "white",hjust=0, x=0.1),
             tbody.style = tbody.style)) %>%
  tab_add_hline(at.row = 1:2, row.side = "top", linewidth = 2)%>%
  table_cell_font(., row = 3, column = 6, face = "bold") %>% 
  table_cell_font(., row = 2, column = 6, face = "bold") %>% 
  tab_add_hline(at.row = c(6), row.side = "bottom", 
                linewidth = 3, linetype = 1) %>% 
  table_cell_font(., row = 2:6, column = 1,
                     size = 11.3)

#%>%
  #tab_add_footnote(
   # text = "*p values in Bold are significant using \n an alpha value of 0.05",
    #size = 10, face = "italic")

Permanova_grouped


ggsave('perma_16S.pdf',
  width = 6, height = 2, dpi = 300, plot =Permanova_grouped)
#ggsave('../../Figures_final/pca_all.pdf',
 #    width = 6, height = 2, dpi = 300, plot =pca)
leg<- get_legend(pca)
part1<- plot_grid(leg, NULL, ncol = 2)
part2<- plot_grid(part1, Permanova_grouped, nrow = 2, labels = c("", "b)"), vjust = 0, rel_heights = c(1,2))
part3<- plot_grid(pca+theme(legend.position = "none"),
                  part2, ncol = 2, rel_widths =  c(1.2,1), labels = c("a)", ""))
```



